### ISSUE TITLE
cluster ip address

### ISSUE THREAD

**Issue by penguin02007** [ppouliot/ansible-drbd_virt_cluster#7]
Like Vagrant was telling  us - Using .1 as an ip address will be an issue if we are going to make it routable.
```
==> virt-cl-drbd-0: You assigned a static IP ending in ".1" to this machine.
==> virt-cl-drbd-0: This is very often used by the router and can cause the
==> virt-cl-drbd-0: network to not work properly. If the network doesn't work
==> virt-cl-drbd-0: properly, try changing this IP.
```

https://github.com/ppouliot/ansible-drbd_virt_cluster/blob/master/Vagrantfile#L43

```
        v.vm.network "private_network", ip: "192.168.1.1"
```

**Comment by ppouliot** [comment]
Technically,  if you read the network config you would see that represents a subnet of 2 IP addresses,  for a link connected by a crossover cable.   Please read the readme to understand the specific goals of this project.  That address is specific to the interface used for replication there will never be routing.
